name: cloud_bites_driver
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+16

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: 2.0.17
  country_code_picker: ^3.3.0
  fluttertoast: ^8.2.2
  pinput: ^5.0.1
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  dropdown_button2: ^2.3.9
  location: ^5.0.0
  google_maps_flutter:
  google_places_flutter: ^2.1.0
  geolocator:
  http: ^1.3.0
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.3
  geocoding: ^3.0.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.4
  dio: ^5.3.2
  connectivity_plus: any
  google_sign_in: ^6.2.2
  awesome_notifications: ^0.10.1
  socket_io_client: ^2.0.0
  slide_to_act: ^2.0.1
  google_maps_webservice2: ^1.0.5
  flutter_polyline_points: ^2.1.0
  webview_flutter: ^4.4.2
  flutter_spinkit: ^5.2.0
  intl: ^0.20.2
  collection: ^1.17.2
  flutter_facebook_auth: ^7.1.2
  url_launcher: ^6.1.11
  fl_chart: ^0.64.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/.env

  fonts:
    - family: GeneralSans-Regular
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
    - family: GeneralSans-Light
      fonts:
        - asset: assets/fonts/GeneralSans-Light.otf
    - family: GeneralSans-Medium
      fonts:
        - asset: assets/fonts/GeneralSans-Medium.otf
    - family: GeneralSans-SemiBold
      fonts:
        - asset: assets/fonts/GeneralSans-SemiBold.otf
    - family: GeneralSans-Bold
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.otf
    - family: GeneralSans-Extralight
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
    - family: GeneralSans-Italic
      fonts:
        - asset: assets/fonts/GeneralSans-Italic.otf
    - family: GeneralSans-LightItalic
      fonts:
        - asset: assets/fonts/GeneralSans-LightItalic.otf
    - family: GeneralSans-MediumItalic
      fonts:
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
    - family: GeneralSans-SemiBoldItalic
      fonts:
        - asset: assets/fonts/GeneralSans-SemiBoldItalic.otf
    - family: GeneralSans-BoldItalic
      fonts:
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
    - family: GeneralSans-ExtralightItalic
      fonts:
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf


