// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// //* Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5YIiWRF7MeoibljbEMC4ORjs9v8xMNGw',
    appId: '1:524176041811:web:701d6724161682c27123a6',
    messagingSenderId: '524176041811',
    projectId: 'cloudbitesbw-51508',
    authDomain: 'cloudbitesbw-51508.firebaseapp.com',
    storageBucket: 'cloudbitesbw-51508.firebasestorage.app',
    measurementId: 'G-X8LSYG2GQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDASK3pVdsSZTlXZ1Tqjt8Nbqy28NK4fKI',
    appId: '1:524176041811:android:0717e95bb352e8307123a6',
    messagingSenderId: '524176041811',
    projectId: 'cloudbitesbw-51508',
    storageBucket: 'cloudbitesbw-51508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Y1d1Pad9skaz7JuiYFUrIlDNxBSl4OI',
    appId: '1:524176041811:ios:f86f72f0209101397123a6',
    messagingSenderId: '524176041811',
    projectId: 'cloudbitesbw-51508',
    storageBucket: 'cloudbitesbw-51508.firebasestorage.app',
    androidClientId: '524176041811-2vq7hpf091cc9mb83hnoul8tupbsse15.apps.googleusercontent.com',
    iosClientId: '524176041811-sbsdf49l6hjvpad819a2al2f8r37s3vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudBitesDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Y1d1Pad9skaz7JuiYFUrIlDNxBSl4OI',
    appId: '1:524176041811:ios:f86f72f0209101397123a6',
    messagingSenderId: '524176041811',
    projectId: 'cloudbitesbw-51508',
    storageBucket: 'cloudbitesbw-51508.firebasestorage.app',
    androidClientId: '524176041811-2vq7hpf091cc9mb83hnoul8tupbsse15.apps.googleusercontent.com',
    iosClientId: '524176041811-sbsdf49l6hjvpad819a2al2f8r37s3vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudBitesDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5YIiWRF7MeoibljbEMC4ORjs9v8xMNGw',
    appId: '1:524176041811:web:95a593af08f832927123a6',
    messagingSenderId: '524176041811',
    projectId: 'cloudbitesbw-51508',
    authDomain: 'cloudbitesbw-51508.firebaseapp.com',
    storageBucket: 'cloudbitesbw-51508.firebasestorage.app',
    measurementId: 'G-B857SGYFX7',
  );
}
